CREATE TABLE IF NOT EXISTS EVENIMENTE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_OWNER INT NOT NULL,
    nume VARCHAR(30) UNIQUE,
    locatie VARCHAR(30),
    descriere VARCHAR(30),
    numarLocuri INT
);

CREATE TABLE IF NOT EXISTS PACHETE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_OWNER INT NOT NULL,
    nume VARCHAR(30) UNIQUE,
    locatie VARCHAR(30),
    descriere VARCHAR(30),
    numarLocuri INT
);

CREATE TABLE IF NOT EXISTS BILETE(

    COD varchar(100) PRIMARY KEY,
    PachetID INT,
    EvenimentID INT,
    FOREIGN KEY(PachetID) REFERENCES PACHETE(ID),
    FOREIGN KEY(EvenimentID) References EVENIMENTE(ID)

);

CREATE TABLE IF NOT EXISTS JOIN_PE(
    PachetID INT,
    EvenimentID INT,
    numarLocuri INT,
    PRIMARY KEY (PachetID, EvenimentID),
    FOREIGN KEY (PachetID) REFERENCES PACHETE(ID),
    FOREIGN KEY (EvenimentID) REFERENCES EVENIMENTE(ID)
);

